### ISSUE TITLE
createMOFAobject() function - error with view names

### ISSUE THREAD

**Issue by QinqinHuang** [bioFAM/MOFA#19]
Hi,

I tried to create a MOFA object from an existing list. The names of the list is not NULL, but createMOFAobject() assigns new view names for it. I had a look at it and I think here:

   if(!is.null(names(data))) {     ## it should be if(is.null(names(data))), right?
     warning(paste0("View names are not specified in the data, renaming them to: ", paste0("view_",1:length(data), collapse=", "), "\n"))
     names(data) <- paste("view",1:length(data), sep="_")
   }

Thanks for this tool! I'm really interested to apply it on my dataset.

**Comment by rargelaguet** [comment]
Hi Qinqin,
you are right, i just introduced this bug in my last commit. It is fixed now, thanks!

**Comment by QinqinHuang** [comment]
Thanks, Ricard!

**Comment by QinqinHuang** [comment]
Hi Ricard,

I feel something is still going on there.. If I run:

data("CLL_data"); MOFAobject <- createMOFAobject(CLL_data)
MOFAobject

The view names are still missing:
Untrained MOFA model with the following characteristics: 
  Number of views: 4 
  View names:  
  Number of features per view: 310 4248 5000 69
  Number of samples: 200 

And apparently when trying to plot using plotTilesData(), the colour values can not be assigned either.

I did not have this issue yesterday.. I think this happened since your last commit & I reinstalled the package :)

Thanks,
Qinqin

**Comment by rargelaguet** [comment]
Apologies, didn't quite fix it :)
Can you try now?

**Comment by QinqinHuang** [comment]
Yeah it's working now. Thank you!
